site_name: Digital Preservation Service
# site_url: https://example.com/

repo_name: Digital Preservation Service
repo_url: https://github.com/Dans-labs/ddps-docs/issues

dev_addr: "127.0.0.1:8080"

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - json

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: False
      use_pygments: False
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true

nav:
  - Notification Driven Archiving: index.md

plugins:
    - search
    - markdownextradata: {}
    - mermaid2

extra:
  hyperlink:
    ext:
      dice: https://www.dice-eosc.eu/
    api:
      ldn-inbox: https://github.com/ekoi/ldn-inbox-service
