site_name: DICE Digital Preservation Service
# site_url: https://example.com/

repo_name: DICE Digital Preservation Service
repo_url: https://github.com/Dans-labs/ddps-docs

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - json

include_homepage_in_sidebar: false

nav:
  - Architecture overview: index.md
  - Introduction: intro.md
  - Components: components.md
  - Open Standards: standards.md

plugins:
    - search
    - markdownextradata: {}

extra:
  api:
    ldn-inbox: https://github.com/ekoi/ldn-inbox-service
